### ISSUE TITLE
It creates just an empty folder without subfolders

### ISSUE THREAD

**Issue by vorant** [SbokyZahodi/fsd-slices#1]
[Screencast_30.03.2024_17:03:32.webm](https://github.com/SbokyZahodi/fsd-slices/assets/4313099/274b03e8-b001-41b5-b27e-6d74046fb6c6)

**Comment by SbokyZahodi** [comment]
Hi! Thanks for the issue. Can you tell us more about what extension settings you have? 

I will also be glad if you tell me which OS you are using and did you have any other vs code instances open at that time?

**Comment by vorant** [comment]
- I use default settings
- Ubuntu 20.04.6 LTS
- opened only one instance of VS Code

I use Nextjs template with `app` folder, if it could helps you
![image](https://github.com/SbokyZahodi/fsd-slices/assets/4313099/50cc2785-58fe-4d96-88c4-1da52fc2a69f)

**Comment by vorant** [comment]
I found the error.
It doesn't work with default templates. I must create `__slice` folder with subfolders. Only with this folder it works well.

![image](https://github.com/SbokyZahodi/fsd-slices/assets/4313099/fc5789e9-bb79-486a-bd07-89a4e9b369be)

**Comment by SbokyZahodi** [comment]
> I found the error. It doesn't work with default templates. I must create `__slice` folder with subfolders. Only with this folder it works well.
> 
> ![image](https://private-user-images.githubusercontent.com/4313099/319044076-fc5789e9-bb79-486a-bd07-89a4e9b369be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMjQxNzIsIm5iZiI6MTcxMjEyMzg3MiwicGF0aCI6Ii80MzEzMDk5LzMxOTA0NDA3Ni1mYzU3ODllOS1iYjc5LTQ4NmEtYmQwNy04OWE0ZTliMzY5YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDNUMDU1NzUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmE0ZDQwMmY2NWE5NzY2NTg4YzNmNDFiNjhkZDQwMmFhZDA0NmQyMTFjODdmYTM5MmM0M2IwNjY4Nzc0ZGE3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vS3AkPnTvq-K8sDuYygZfR48NDVMdLADbyv2M0XsgpU)


You have the "custom template" setting enabled, which allows you to create your own custom template. This is written in the readme. Turn it off and everything will work

**Comment by vorant** [comment]
by some reason `custom template` was true in my case but I hadn't checked manually.
thank you!
