### ISSUE TITLE
Does not create a folder structure

### ISSUE THREAD

**Issue by PavelMelnik94** [SbokyZahodi/fsd-slices#2]
| steps|
|--------|
| <img width="470" alt="image" src="https://github.com/SbokyZahodi/fsd-slices/assets/74857928/a78022b0-ae87-465b-9773-91741cabda06">|
| <img width="469" alt="image" src="https://github.com/SbokyZahodi/fsd-slices/assets/74857928/9a311c81-db20-4320-85d3-75462e66f741"> |
|<img width="141" alt="image" src="https://github.com/SbokyZahodi/fsd-slices/assets/74857928/8dd1eee3-2536-459e-92e9-234a43be7b2d"> |
| <img width="815" alt="image" src="https://github.com/SbokyZahodi/fsd-slices/assets/74857928/0fc06df8-28c4-4b6b-abc8-0ae54edec827"> | 

api, config, ui, model ?!

**Comment by SbokyZahodi** [comment]
Please turn off the custom template setting  https://github.com/SbokyZahodi/fsd-slices/issues/1

**Comment by PavelMelnik94** [comment]
I understand the principle. Thank you. It works!
