### ISSUE TITLE
Can I customize a template code? 

### ISSUE THREAD

**Issue by Mintnoii** [SbokyZahodi/fsd-slices#4]
Such as custom vue components, or adding a piece of code to the api file to automatically import shared/api? 
```
<template>
  <div>

  </div>
</template>

<script setup lang="ts">

</script>

<style  lang="scss" scoped>

</style>
```
If it can be achieved, then users can quickly implement this fsd architecture file according to their own project needs!

**Comment by SbokyZahodi** [comment]
Hi! There has already been such functionality. Unfortunately, some users had problems with this setting (for example, https://github.com/SbokyZahodi/fsd-slices/issues/1) and I took it away. I will think about how this can be solved and release soon.

**Comment by Mintnoii** [comment]
Thanks for your reply, I have turned this issue off, looking forward to your repair!
